### ISSUE TITLE
板主名單有特殊字元出錯

### ISSUE THREAD

**Issue by LaplusIjns** [PyPtt/PyPtt#102]
高雄板 板主名單  ilovemami/さくらみこ/兎田ぺこら
分割 板主字串 獲得 板主名單
讀取到 兎 字
出錯 UnicodeEncodeError 
'big5' codec can't encode character '\u514e' in position 0: illegal multibyte sequence

詳細位置
    _api_get_board_info.py
    get_board_info()
    if len(c.encode('big5')) > 1:

建議新增例外處理 

try:
    if len(c.encode('big5')) > 1:
        check = False
        break
except UnicodeEncodeError:
    check = False
    break

**Comment by PttCodingMan** [comment]
Ok, let me check.

**Comment by PttCodingMan** [comment]
@LaplusIjns 1.0.8 should works fine now.

https://github.com/PyPtt/PyPtt/blob/7dc741279fb1e37eb1011290dbd7471770163c15/PyPtt/_api_get_board_info.py#L100
