### ISSUE TITLE
PTT 推文時, 推文會出現亂碼

### ISSUE THREAD

**Issue by yehchge** [PyPtt/PyPtt#158]
PTT 推文時, 推文會出現亂碼.

原因: PTT 帳號長度只有 12 位元
FYI: https://www.ptt.cc/bbs/PttNewhand/M.1482462427.A.3CC.html

目前最短要4個字元. (PS: 之前的帳號還有兩個字元的).

在 PTT 上輸入 12 位元的帳號, 能登入, 在 12  位元之後加上其他字元, 
也能登入. 因為輸入上只能輸入 12 位元.

但是使用 PyPtt 套件登入時, 使用 12 位元後面在加上其他字元, 
還是能登入, 但是登入後推文時, 就會出現亂碼.

有稍微看一下程式, 可能是因為會以輸入進來的帳號長度,
去抓取處理推文, 不知道是否是這個原因?!

照理說, 帳號不應該出現 13 個位元.

正常使用是不會有問題的.

備註: 密碼最多 8 個字元.

**Comment by PttCodingMan** [comment]
Hi @yehchge, please help check the fixed PR.
https://github.com/PyPtt/PyPtt/pull/159
