### ISSUE TITLE
較高效的刷新推文

### ISSUE THREAD

**Issue by daviddwlee84** [PyPtt/PyPtt#65]
目前 [`PostInfo`](https://github.com/PttCodingMan/PyPtt/blob/4e65cec1992821f8baeb583463b187328c39667e/PyPtt/data_type.py#L189) 是一個靜態的data type嘛
感覺如果能夠新增 `fetch_new_push()` 之類的 method
從尾頁開始往回 parse 直到 parse 到重覆的推文
來更新 `push_list` 也許是個好的 idea
就不用每次都用 [`get_content()`](https://github.com/PttCodingMan/PyPtt/blob/4e65cec1992821f8baeb583463b187328c39667e/PyPtt/_api_util.py#L19) 來 crawl 整篇文再 parse
例如一些閒聊文或實況文就挺適合用這個 feature 的 :D

如果覺得可行 看看我也能幫忙implement一下

**Comment by PttCodingMan** [comment]
可以的喔 👍

**Comment by wenfey** [comment]
今天在試用，也有同樣想法！！

**Comment by PttCodingMan** [comment]
我覺得如果不存在一種指令，可以高效率更新文章。
這應該算是 PyPtt 的一種應用實例。

我會放在 [使用範例](https://pyptt.cc/examples.html) 這一塊。
