### ISSUE TITLE
PyPtt 支援 PTT API 連線方式

### ISSUE THREAD

**Issue by PichuChen** [PyPtt/PyPtt#71]
目前 PTT APP 的 API 正在開發中，不過缺少 Client 端的測試工具。

因此應該可以透過 PyPtt 做新連線方式的測試

透過 PyPTT 進行測試 原有Telnet版的執行時間如下：

real	0m1.601s
user	0m0.989s
sys	0m0.221s

real	0m1.507s
user	0m0.980s
sys	0m0.181s

real	0m1.560s
user	0m1.011s
sys	0m0.198s

HTTPS 版的執行時間如下

real	0m1.778s
user	0m0.319s
sys	0m0.109s

real	0m1.673s
user	0m0.297s
sys	0m0.082s

real	0m1.645s
user	0m0.277s
sys	0m0.068s

因此實際上有潛力作為較高效率的連線方式。

**Comment by PttCodingMan** [comment]
感謝 QvQ
