### ISSUE TITLE
Failed to connect to PTT while PTT2 is Good

### ISSUE THREAD

**Issue by submarine35** [PyPtt/PyPtt#88]
I'm using below code snippet from PyPtt to test WebSocket connection.
For PTT2 it is good. However, I got Connection Refused Failure for PTT.
Please check the screenshots
![2022-01-01_17-43-35](https://user-images.githubusercontent.com/96939171/147848079-31565435-6c7d-4da0-ab9f-d1595f77f6ab.jpg)
![2022-01-01_17-43-53](https://user-images.githubusercontent.com/96939171/147848080-5b5e65c3-523c-4b45-9460-5c1373decb46.jpg)

`import websockets.http
import websockets
import websockets.http
import asyncio

websocket_host = 'wss://ws.ptt.cc/bbs/'
websocket_origin = 'https://term.ptt.cc'

ss= asyncio.get_event_loop().run_until_complete(websockets.connect(websocket_host,origin=websocket_origin))`

**Comment by PttCodingMan** [comment]
Hi 
As far as I know, all cloud hosts have been blocked by PTT.

The next version of PyPtt is trying to bypass this restriction.
