### ISSUE TITLE
編輯紅包袋

### ISSUE THREAD

**Issue by zhixx** [PyPtt/PyPtt#89]
希望能有編輯紅包袋內文(或標題)的功能
這樣在發批幣時，就可以向收件人說明這一筆獎金的名目

**Comment by PttCodingMan** [comment]
ok

**Comment by GniN** [comment]
我幫這個功能做了PR
https://github.com/PttCodingMan/PyPtt/pull/90

**Comment by PttCodingMan** [comment]
Thanks.

已經 merge!
